create extension if not exists pgcrypto;

create type public.user_role as enum ('guru','kepala_sekolah');
create type public.user_status as enum ('aktif','nonaktif');
create type public.leave_status as enum ('pending','approved','rejected');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nama text not null,
  username text unique,
  role public.user_role not null default 'guru',
  status public.user_status not null default 'aktif',
  created_at timestamptz not null default now()
);

create table public.attendance (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  tanggal date not null,
  jam_hadir timestamptz,
  jam_pulang timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id,tanggal),
  constraint pulang_requires_hadir check (jam_pulang is null or jam_hadir is not null)
);

create table public.leave_types (
  id bigint generated by default as identity primary key,
  nama text not null unique,
  aktif boolean not null default true
);

create table public.leave_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  leave_type_id bigint not null references public.leave_types(id),
  tanggal_mulai date not null,
  tanggal_selesai date not null,
  alasan text not null,
  lampiran text,
  status public.leave_status not null default 'pending',
  approved_by uuid references public.profiles(id),
  approved_at timestamptz,
  catatan_approval text,
  created_at timestamptz not null default now(),
  constraint valid_dates check (tanggal_selesai >= tanggal_mulai)
);

create index attendance_user_date_idx on public.attendance(user_id,tanggal desc);
create index leave_requests_status_idx on public.leave_requests(status);

insert into public.leave_types(nama) values
('Cuti Sakit'),('Cuti Hamil / Melahirkan'),('Cuti Tahunan'),
('Izin Keperluan Penting'),('Cuti Tanpa Gaji'),('Lainnya')
on conflict (nama) do nothing;

alter table public.profiles enable row level security;
alter table public.attendance enable row level security;
alter table public.leave_types enable row level security;
alter table public.leave_requests enable row level security;

create or replace function public.is_kepala()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='kepala_sekolah' and status='aktif') $$;

create policy "profiles own read" on public.profiles for select to authenticated using (id=auth.uid() or public.is_kepala());
create policy "kepala manage profiles" on public.profiles for all to authenticated using (public.is_kepala()) with check (public.is_kepala());

create policy "attendance own read" on public.attendance for select to authenticated using (user_id=auth.uid() or public.is_kepala());
create policy "attendance own insert" on public.attendance for insert to authenticated with check (user_id=auth.uid());
create policy "attendance own update" on public.attendance for update to authenticated using (user_id=auth.uid() and not public.is_kepala()) with check (user_id=auth.uid());
create policy "kepala attendance all" on public.attendance for all to authenticated using (public.is_kepala()) with check (public.is_kepala());

create policy "leave types read" on public.leave_types for select to authenticated using (true);
create policy "leave own read" on public.leave_requests for select to authenticated using (user_id=auth.uid() or public.is_kepala());
create policy "leave own insert" on public.leave_requests for insert to authenticated with check (user_id=auth.uid() and status='pending');
create policy "kepala leave update" on public.leave_requests for update to authenticated using (public.is_kepala()) with check (public.is_kepala());
